version: '3'

services:
  zookeeper1:
    image: docker.io/bitnami/zookeeper:3-debian-10
    hostname: zookeeper1
    ports: ["2181:2181"]
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka1:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    hostname: kafka1
    environment:
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper1:2181
    ports: ["9092:9092"]
    depends_on: ["zookeeper1"]